server:
  port: 8500
  servlet:
    context-path: /

openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 60000
    connect-timeout: 60000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

logging:
  level:
    com.exadmax.chatgpt.openai.service: TRACE

# Spring
spring:
  jackson:
    default-property-inclusion: NON_NULL

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    circuitbreakers:
      enabled: true
